// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEox8i1Vmn8qjcdncxa1B4u9_aMtNkRos',
    appId: '1:592976471472:web:631c2f3fa2a8f17fd36275',
    messagingSenderId: '592976471472',
    projectId: 'tamini-app-food',
    authDomain: 'tamini-app-food.firebaseapp.com',
    storageBucket: 'tamini-app-food.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCWEseoH1sC3fi_g9FkqMyXkPV3Bes6I',
    appId: '1:592976471472:android:730c29beee411326d36275',
    messagingSenderId: '592976471472',
    projectId: 'tamini-app-food',
    storageBucket: 'tamini-app-food.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfW2yGEPt-vHquq2KT1fbrVVsWqeU9mM',
    appId: '1:592976471472:ios:b6a16e079bbb2542d36275',
    messagingSenderId: '592976471472',
    projectId: 'tamini-app-food',
    storageBucket: 'tamini-app-food.firebasestorage.app',
    iosBundleId: 'com.tamini.tamini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQfW2yGEPt-vHquq2KT1fbrVVsWqeU9mM',
    appId: '1:592976471472:ios:b6a16e079bbb2542d36275',
    messagingSenderId: '592976471472',
    projectId: 'tamini-app-food',
    storageBucket: 'tamini-app-food.firebasestorage.app',
    iosBundleId: 'com.tamini.tamini',
  );
}
